#macro WINDOW_WIDTH 1280
#macro WINDOW_HEIGHT 720

#macro BASE_RESOLUTION_WIDTH 640
#macro BASE_RESOLUTION_HEIGHT 360

#macro BASE_CAMERA_WIDTH BASE_RESOLUTION_WIDTH
#macro BASE_CAMERA_HEIGHT BASE_RESOLUTION_HEIGHT
