
enum BattleState
{
	NEUTRAL,
	PLAYER_TURN_STANDBY,
	PLAYER_TURN_FREE,
	PLAYER_TURN_UNIT_OPTIONS,
	PLAYER_TURN_SYSTEM_OPTIONS,
	PLAYER_TURN_MOVE,
	PLAYER_TURN_ATTACK,
	PLAYER_TURN_INFO,
	PLAYER_TURN_POST_MOVE_OPTIONS
}
